adult/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from adult.views import *

urlpatterns = [
    path('enter_file/', FileCreateView.as_view(), name='get_file'),
    path('contest_type/<int:file_pk>/', get_contest_type, name='get_contest_type'),
    path('contest_value/<int:file_pk>/', ContestValueCreateView.as_view(), name='get_contest_value'),
    path('contest_relative/<int:file_pk>/', ContestRelativeCreateView.as_view(),
       name='get_contest_relative'),
]

german/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from german.views import *

urlpatterns = [
    # path('enter_file/', FileCreateView.as_view(), name='get_file'),
    # path('contest_type/<int:file_pk>/', get_contest_type, name='get_contest_type'),
    path('contest_value/<int:file_pk>/', ContestValueCreateView.as_view(), name='get_contest_value'),
    # path('contest_relative_first/<int:plaintiff_file_pk>/', RelativeFileCreateView.as_view(), name='get_contest_relative'),
    path('contest_relative_second/<int:file_pk>/', ContestRelativeCreateView.as_view()),
]

justifyinter/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from german.views import *
from mladvocate.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', WelcomeView.as_view(), name='welcome_page'),
    path('presentation/', PresentationView.as_view(), name='presentation'),
    url(r'^mla/', include(('mladvocate.urls', 'mladvocate'), namespace='mladvocate')),
    url(r'^german/', include(('german.urls', 'german'), namespace='german')),
    # url(r'^adult/', include(('adult.urls', 'adult'), namespace='adult')),
    path('value_justification/german/<int:pk>/', ContestValueGerman.as_view(), name='value_justification'),
    # path('value_justification/adult/<int:pk>/', ContestValueAdult.as_view(), name='value_justification'),
    path('relative_justification/german/<int:pk>/', ContestRelativeGerman.as_view(), name='relative_justification'),
    # path('relative_justification/adult/<int:pk>/', ContestRelativeAdult.as_view(), name='relative_justification'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

german/forms.py
import pandas as pd
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit

from django.forms import ModelForm
from german.models import *
from mladvocate.signals import convert_operator
from mladvocate.utils import *
from generate_justifications.dataset.load_data_and_model import load_model



class ContestValueForm(ModelForm):
    class Meta:
        model = GermanContestValue
        exclude = ['file', 'target_output']

    def __init__(self, *args, **kwargs):
        file = kwargs.pop('file', None)
        super(ContestValueForm, self).__init__(*args, **kwargs)
        self.file = file

    helper = FormHelper()
    # helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-12'
    helper.field_class = 'col-lg-12'
    helper.form_show_labels = False


    def clean(self, *args, **kwargs):
        """
        In here you can validate the two fields
        raise ValidationError if you see anything goes wrong.
        for example if you want to make sure that field1 != field2
        """
        data = super().__dict__
        cleaned_data = super().clean()
        f_names = [f.name for f in GermanContestValue._meta.get_fields()]
        model_fields = {name.replace('_operator', '').replace('_value', '')
                        for name in f_names if '_operator' in name or '_value' in name}
        for field in list(model_fields):
            field_op = cleaned_data[field + '_operator']
            field_val = cleaned_data[field + '_value']
            if (field_op is None) != (field_val is None):
                self._errors[field + '_value'] = ["L'opérateur et la valeur doivent être remplis ou laissés vides"]  # Will raise a error message
            if ((field_op is not None) and
                not convert_operator(field_op)(self.file.__dict__[field], field_val)):
                self._errors[field + '_value'] = ["Le dossier doit satisfaire cette contrainte"]  # Will raise a error message
        return cleaned_data


class ContestRelativeForm(ModelForm):
    class Meta:
        model = GermanContestRelative
        exclude = ['plaintiff_file', 'relative_file', 'target_plaintiff', 'output_relative']

    def __init__(self, *args, **kwargs):
        plaintiff_file = kwargs.pop('plaintiff_file', None)
        relative_file = kwargs.pop('relative_file', None)
        super(ContestRelativeForm, self).__init__(*args, **kwargs)
        self.plaintiff_file = plaintiff_file
        self.relative_file = relative_file


    helper = FormHelper()
    # helper.form_class = 'form-horizontal'
    helper.label_class = 'col-lg-12'
    helper.field_class = 'col-lg-12'
    helper.form_show_labels = False

    def clean(self, *args, **kwargs):
        """
        In here you can validate the two fields
        raise ValidationError if you see anything goes wrong.
        for example if you want to make sure that field1 != field2
        """
        cleaned_data = super().clean()
        f_names = [f.name for f in GermanContestRelative._meta.get_fields()]
        model_fields = {name.replace('_operator', '')
                        for name in f_names if '_operator' in name or '_value' in name}
        for field in list(model_fields):
            field_op = cleaned_data[field + '_operator']
            if field_op is not None:
                cond = convert_operator(field_op)(
                    self.plaintiff_file.__dict__[field], self.relative_file.__dict__[field]
                )
                if not cond:
                    self._errors[field + '_operator'] = ["Les dossiers doivent satisfaire cette contrainte"]  # Will raise a error message

        return cleaned_data

german/views.py
import pandas as pd

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.shortcuts import redirect

from german.forms import ContestValueForm, ContestRelativeForm
from german.models import *
from generate_justifications.dataset.load_data_and_model import load_model


def welcome_page(request):
    return render(request, 'home.html')


class ContestValueCreateView(CreateView):
    def get(self, request, *args, **kwargs):
        file = GermanFile.objects.get(pk=self.kwargs['file_pk'])
        context = {'form': ContestValueForm(file=file), 'file': file.__dict__}
        return render(request, 'german_contest_value_form.html', context)

    def post(self, request, *args, **kwargs):
        file = GermanFile.objects.get(pk=self.kwargs['file_pk'])
        form = ContestValueForm(request.POST, file=file)
        if form.is_valid():
            contest_value = form.save(commit=False)
            contest_value.file = file
            contest_value.target_output = 1 - file.__dict__['y_pred']
            contest_value.save()
            return HttpResponseRedirect('/value_justification/german/' + str(contest_value.pk))
        return render(request, 'german_contest_value_form.html', {'form': form, 'file': file.__dict__})


class ContestRelativeCreateView(CreateView):
    def get(self, request, *args, **kwargs):
        plaintiff_file = GermanFile.objects.get(pk=self.kwargs['file_pk'])
        relative_file = GermanFile.objects.get(pk=request.session['relative_file_pk'])
        context = {'form': ContestRelativeForm(plaintiff_file=plaintiff_file, relative_file=relative_file),
                   'plaintiff_file': plaintiff_file.__dict__,
                   'relative_file': relative_file}
        return render(request, 'german_contest_relative_form.html', context)

    def post(self, request, *args, **kwargs):
        plaintiff_file = GermanFile.objects.get(pk=self.kwargs['file_pk'])
        relative_file = GermanFile.objects.get(pk=request.session['relative_file_pk'])
        form = ContestRelativeForm(request.POST, plaintiff_file=plaintiff_file, relative_file=relative_file)
        if form.is_valid():
            contest_relative = form.save(commit=False)
            contest_relative.plaintiff_file = plaintiff_file
            contest_relative.relative_file = relative_file
            contest_relative.target_plaintiff = 1 - plaintiff_file.__dict__['y_pred']
            contest_relative.output_relative = relative_file.__dict__['y_pred']
            contest_relative.save()
            return HttpResponseRedirect('/relative_justification/german/' + str(contest_relative.pk))
        return render(request, 'german_contest_relative_form.html', {'form': form, 'plaintiff_file': plaintiff_file.__dict__, 'relative_file': relative_file})

templates/german/adult_contest_relative_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h2>Contestation by comparison with another file</h2>
<p>Currently, my file is predicted
    <strong>
    {% if file.y_pred %}
        >50K
    {% else %}
        <=50K
    {% endif%}</strong>. I think my file should have been predicted as:</p>
  <form method="post">
    {% csrf_token %}
    <div>
            {{ form.target_plaintiff|as_crispy_field }}
    </div>
Knowing that an other file I have knowledge about have been:
    <div>
            {{ form.output_relative|as_crispy_field }}
    </div>
and that (leave blank unwanted features):
<br><br>
    <div>
        <div class="form-row">
          <div class="form-group col-md-6 mb-0">
              <h3>Feature of your file</h3>
          </div>
          <div class="form-group col-md-6 mb-0">
            <h3>Compared to other's features</h3>
          </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.age_operator|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                Other's age
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.workclass_operator|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                Other's workclass
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.education_operator|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                Other's education
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.education_num_operator|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                Other's education_num
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.marital_status_operator|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                Other's marital_status
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.occupation_operator|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                Other's occupation
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.relationship_operator|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                Other's relationship
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.race_operator|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                Other's race
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.sex_operator|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                Other's sex
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.capital_gain_operator|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                Other's capital_gain
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.capital_loss_operator|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                Other's capital_loss
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.hours_per_week_operator|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                Other's hours_per_week
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
              {{ form.native_country_operator|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 mb-0">
                Other's native_country
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Send</button>
  </form>
{% endblock %}

templates/german/adult_contest_type.html
{% extends 'base.html' %}

{% block content %}
<h5 id="headings">Type of contestation</h5>
<p>
    Our model, based on adult income data set, has predicted that your annual income is
    <strong>
        {% if file.y_pred %}
            >50K
        {% else %}
            =<50K
        {% endif %}
    </strong>
</p>
<p>
    Our tool allows you to challenge this decision. If you wish to process, the next step is to
    create a challenge to argue why you think that the decision was not the correct one.
    The decision is only based on the values of your file so does the challenge. Through our interface, you
    will be able to point out which features our your file should irrevocably lead to
    a different output of the decision system.
</p>
<p>
    Two types of challenges are allowed by our system:
</p>

<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Your values only</h5>
        <p class="card-text">
            Compare the values of your file directly to thresholds that you define. <br>
            e.g.: since my occupation is 'Exec-managerial' and since I work more than 40 hours per week,
            I think that the model should have predicted my income as >50k.
        </p>
        <button onclick="window.location.href = '{% url 'adult:get_contest_value' file_pk=file_pk %}';" class="btn btn-primary" type="button">Contest with your values</button>      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card bg-secondary">
      <div class="card-body">
        <h5 class="card-title">Relatively to another file <br>
            <i class="fa fa-warning"></i> WORK IN PROGRESS</h5>
        <p class="card-text">
            Compare your file to another file for which you know the output. It is useful to express
            a feeling of inequity of treatment. <br>
            e.g.: My neighbor's income was classified has >50k. Since we have the same occupation
            and since my capital loss is lower than his, I think that my income should have been classified
            as >50k as well.
        </p>
        <button class="btn btn-secondary" type="button">Contest relatively to another file</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/german/adult_contest_value_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<h5 id="headings">Contestation form </h5>
<p>Currently, your predicted income is
    <strong>
        {% if file.y_pred %}
            >50K
        {% else %}
            <=50K
        {% endif%}
    </strong>,
    and you think that it should have been classified as
    <strong>
        {% if file.y_pred %}
            <=50k
        {% else %}
            >50K
        {% endif%}
    </strong>.
</p>
<p>
    You are here to challenge the prediction made by our model. To do so
    please fill out the following form by specifying a set of conditions
    , which you satisfy, and that should irrevocably lead to a classification
    as
    <strong>
        {% if file.y_pred %}
            <=50k
        {% else %}
            >50K
        {% endif%}
    </strong> from your point of view.
</p>
<p>
    <strong>How to fill it?</strong><br>
    For each feature, you can specify an operator (IS, IS NOT, >, <, ...) and a value.
    You can also leave the fields blank. This will be the set of conditions.
    Here is an example of how your contestation could look like at the end: <br>
        <i>
            <dd>
                Knowing that my education IS 'HS-Grad',
                that my hours per week >= 38, and that my race is White <br>
                I think that the model should have predicted my income as <strong>>50k</strong>.
            </dd>
        </i>
</p>
<div class="card" style="...">
  <div class="card-header">
    <h5 class="card-title">Your contestation</h5>
  </div>
  <div class="card-body">
    <form method="post">
        {% csrf_token %}

      <div id='form-errors'>{{ form_errors }}</div>
        <div>
            <div class="form-row">
              <div class="form-group col-md-8 mb-0">
                  <h6>Feature of your file</h6>
              </div>
              <div class="form-group col-md-4 mb-0">
                <h6>Compared to a value</h6>
              </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                {{form.age_operator.label }} <br>({{  file.age  }})
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{form.age_operator|as_crispy_field }}
                </div>
                <div class="form-group col-md-5 mb-0">
                  {{form.age_value|as_crispy_field }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                {{form.sex_operator.label }} <br>({{  file.sex  }})
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{form.sex_operator|as_crispy_field }}
                </div>
                <div class="form-group col-md-5 mb-0">
                  {{form.sex_value|as_crispy_field }}
                </div>
                    </div>
            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                {{form.race_operator.label }} <br>({{  file.race  }})
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{form.race_operator|as_crispy_field }}
                </div>
                <div class="form-group col-md-5 mb-0">
                  {{form.race_value|as_crispy_field }}
                </div>
                    </div>
            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                {{form.native_country_operator.label }} <br>({{  file.native_country  }})
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{form.native_country_operator|as_crispy_field }}
                </div>
                <div class="form-group col-md-5 mb-0">
                  {{form.native_country_value|as_crispy_field }}
                </div>
                    </div>
            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                {{form.marital_status_operator.label }} <br>({{  file.marital_status  }})
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{form.marital_status_operator|as_crispy_field }}
                </div>
                <div class="form-group col-md-5 mb-0">
                  {{form.marital_status_value|as_crispy_field }}
                </div>
                    </div>
            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                {{form.relationship_operator.label }} <br>({{  file.relationship  }})
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{form.relationship_operator|as_crispy_field }}
                </div>
                <div class="form-group col-md-5 mb-0">
                  {{form.relationship_value|as_crispy_field }}
                </div>
                    </div>
            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                {{form.education_operator.label }} <br>({{  file.education  }})
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{form.education_operator|as_crispy_field }}
                </div>
                <div class="form-group col-md-5 mb-0">
                  {{form.education_value|as_crispy_field }}
                </div>
                    </div>
            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                {{form.education_num_operator.label }} <br>({{  file.education_num  }})
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{form.education_num_operator|as_crispy_field }}
                </div>
                <div class="form-group col-md-5 mb-0">
                  {{form.education_num_value|as_crispy_field }}
                </div>
                    </div>
            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                {{form.hours_per_week_operator.label }} <br>({{  file.hours_per_week  }})
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{form.hours_per_week_operator|as_crispy_field }}
                </div>
                <div class="form-group col-md-5 mb-0">
                  {{form.hours_per_week_value|as_crispy_field }}
                </div>
                    </div>
            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                {{form.workclass_operator.label }} <br>({{  file.workclass  }})
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{form.workclass_operator|as_crispy_field }}
                </div>
                <div class="form-group col-md-5 mb-0">
                  {{form.workclass_value|as_crispy_field }}
                </div>
                    </div>
            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                {{form.occupation_operator.label }} <br>({{  file.occupation  }})
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{form.occupation_operator|as_crispy_field }}
                </div>
                <div class="form-group col-md-5 mb-0">
                  {{form.occupation_value|as_crispy_field }}
                </div>
                    </div>
            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                {{form.capital_gain_operator.label }} <br>({{  file.capital_gain  }})
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{form.capital_gain_operator|as_crispy_field }}
                </div>
                <div class="form-group col-md-5 mb-0">
                  {{form.capital_gain_value|as_crispy_field }}
                </div>
                    </div>
            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                {{form.capital_loss_operator.label }} <br>({{  file.capital_loss  }})
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{form.capital_loss_operator|as_crispy_field }}
                </div>
                <div class="form-group col-md-5 mb-0">
                  {{form.capital_loss_value|as_crispy_field }}
                </div>
                    </div>
        </div>
        <button type="submit" class="btn btn-primary">Save and continue</button>
      </form>

  </div>
</div>

{% endblock %}

templates/german/german_contest_type.html
{% extends 'base.html' %}

{% block content %}
<h5 id="headings">Contestation</h5>
<p>
    Our model machine learning model, based on the data of the german credit dataset, has predicted that your
    file indicates that you are a
    <strong>
        {% if file.y_pred %}
            good
        {% else %}
            bad
        {% endif %}
    </strong>
    applicant.
</p>
<p>
    Our tool allows you to challenge this decision. If you wish to process, the next step is to
    create a challenge to argue why you think that the decision was not the correct one.
    The decision is only based on the values of your file so does the challenge. Through our interface, you
    will be able to point out which features our your file should irrevocably lead to
    a different output of the decision system.
</p>
<p>
    Two types of challenges are allowed by our system:
</p>

<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Your values only</h5>
        <p class="card-text">
            Compare the values of your file directly to thresholds that you define. <br>
            e.g.: since the credit amount is lower than 10000 and since my saving status is higher than 1000,
            I think that my file should have been classified as good.
        </p>
        <button onclick="window.location.href = '{% url 'german:get_contest_value' file_pk=file_pk %}';" class="btn btn-primary" type="button">Contest with your values</button>      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Relatively to another file</h5>
        <p class="card-text">
            Compare your file to another file for which you know the output. It is useful to express
            a feeling of inequity of treatment. <br>
            e.g.: My neighbor has been classified has a good applicant. Since the purposes of our credit are the same
            and since my duration is higher than his, I think that I should have been classified as good as well.
        </p>
        <button onclick="window.location.href = '{% url 'german:get_contest_relative' plaintiff_file_pk=file_pk %}';" class="btn btn-primary" type="button">Contest relatively to another file</button>
      </div>
    </div>
  </div>
</div>


{% endblock %}

templates/german/home.html
{% extends 'base.html' %}

{% block title %} MLA -  Home {% endblock %}

{% block content %}
<h5 id="headings">Bienvenue sur notre outil d’expérimentation en ligne ! </h5>

<p align="justify">
    Cette étude utilisateur est menée dans le cadre de recherches sur l’explicabilité des algorithmes.
    Certains algorithmes sont déjà utilisés pour prendre des décisions qui affectent notre vie quotidienne.
    La recommandation en ligne, l’aide à la décision pour les juges ou pour les demandes de crédits en sont des exemples.
    Puisque nos sociétés sont de plus en plus digitalisées et les algorithmes de plus en plus performants,
    les décisions automatiques vont occuper une part croissante dans les organisations publiques et les entreprises.
</p>
<p align="justify">
    Pour que l’automatisation de ces décisions restent bénéfique à la société, il est important que l’humain garde
    un certain contrôle sur la machine. Il est indispensable par exemple que les utilisateurs soient informés que
    la décision a été prise automatiquement et qu’ils puissent en comprendre les grandes lignes. Aussi, dans le cas
    où la décision affecte directement un individu, il faudrait que ce dernier puisse contester la décision.
    Si cette contestation est valide, elle devrait conduire à une annulation de la décision, dans le cas contraire
    des informations devraient être apportées pour justifier la décision controversée.
</p>
<p align="justify">
    Dans le cadre de nos recherches, nous avons développé un outil (qui en est encore à une phase expérimentale)
    pour contester et justifier les décisions prises par un algorithme basé sur l’apprentissage.
    À la différence des algorithmes classiques qui se contentent d'executer les instructions codées par leur concepteur,
    ces algorithmes apprennent à remplir un objectif précis à partir d'un grand nombre d'exemples.
    On dit donc qu’une décision est justifiée si elle reflètent effectivement ce qui s’observe dans ces exemples.
</p>
<p align="justify">
    Le but de cet expérience et de tester différentes méthodes pour contester / justifier des décisions automatiques.
    Il se présente sous la forme de petits exercices avec une réponse à choix multiple.
    Vous avez aussi la possibilité de laisser des commentaires libres, n’hésitez pas à donner votre avis sur
    les exercices, sur les difficultés que vous rencontrez ou sur les questionnements qui vous viennent.
    Le tout prend environ 30 minutes.
</p>
<br>
<br>
    <a class="btn btn-primary btn-lg btn-block" href="{% url 'presentation' %}" role="button">Continuer</a>
<br>
<br>
<p>
    <b> Qui sommes-nous ?</b> <br>
    Clément Henin et Daniel Le Métayer sont membres de l’équipe PRIVATICS de l’Institut National de Recherche en
    Informatique et Automatique (Inria). Notre projet de recherche s'appelle ML-Advocate
    (pour <i>machine learning advocate</i>, l'avocat de l'apprentissage automatique).
</p>

{% endblock %}

templates/german/relative_file_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h5 id="headings">Contestation form (step 1): enter the reference file </h5>
<p>Currently, your credit application file was classified as
    <strong>
        {% if file.y_pred %}
            good
        {% else %}
            bad
        {% endif%}
    </strong>,
    and you think that it should have been classified as
    <strong>
        {% if file.y_pred %}
            bad
        {% else %}
            good
        {% endif%}
    </strong>.
</p>
<p>
    You wish to contest this decision because you think that your
    file was treated unfairly w.r.t to another file you have some
    knowledge about.
</p>
<p>
    <strong>How to fill it?</strong><br>
    The first step is to enter the reference file with which you wish to be
    compared.
</p>

<div class="card" style="...">
  <div class="card-header">
    <h5 class="card-title">The reference's features</h5>
  </div>
  <div class="card-body">
      {% csrf_token %}
      {% crispy form %}
  </div>
</div>

{% endblock %}